cmake_minimum_required(VERSION 3.28)

# Wide Eye QA tracker: index generator and schema validator.
#
# The issue files under docs/qa/{open,closed} are the source of truth;
# docs/qa/INDEX.md is a generated view of their frontmatter. A hand-maintained
# checklist is the artifact that goes stale first and stops being trusted, so
# this script owns it instead.
#
#   cmake -DMODE=check -P tools/qa/qa-tracker.cmake   validate only; fails on drift
#   cmake -DMODE=index -P tools/qa/qa-tracker.cmake   rewrite docs/qa/INDEX.md
#   cmake -DMODE=next  -P tools/qa/qa-tracker.cmake   print the next free QA id
#
# Equivalent build targets exist once a preset is configured: qa-check,
# qa-index, qa-next. Deliberately dependency-free CMake script rather than a
# new language runtime, matching tests/assert-*.cmake.

if(NOT DEFINED MODE)
    set(MODE check)
endif()
if(NOT MODE MATCHES "^(check|index|next)$")
    message(FATAL_ERROR "Unknown MODE '${MODE}' (expected check, index, or next)")
endif()

get_filename_component(qa_repo_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(qa_dir "${qa_repo_root}/docs/qa")
set(qa_open_dir "${qa_dir}/open")
set(qa_closed_dir "${qa_dir}/closed")
set(qa_index_path "${qa_dir}/INDEX.md")

set(qa_statuses open in-progress fixed wont-fix duplicate not-a-bug)
set(qa_open_statuses open in-progress)
set(qa_severities S1 S2 S3 S4)
set(qa_confidences confirmed plausible unconfirmed)
set(qa_areas core platform render voxel game tests build tools docs)
set(qa_reporters owner agent)
set(qa_required_keys id title status severity confidence area reporter reported)
set(qa_optional_keys phase charter rule platform blocks depends closed fix)
set(qa_list_keys verify)
set(qa_all_keys ${qa_required_keys} ${qa_optional_keys} ${qa_list_keys})

set(qa_severity_label_S1 "S1 — blocks the tracer gate")
set(qa_severity_label_S2 "S2 — major")
set(qa_severity_label_S3 "S3 — minor")
set(qa_severity_label_S4 "S4 — polish")

set_property(GLOBAL PROPERTY qa_errors "")

function(qa_fail file message)
    get_property(errors GLOBAL PROPERTY qa_errors)
    list(APPEND errors "${file}: ${message}")
    set_property(GLOBAL PROPERTY qa_errors "${errors}")
endfunction()

function(qa_check_enum file key value allowed_list_name)
    if(NOT value)
        return()
    endif()
    set(allowed ${${allowed_list_name}})
    if(NOT value IN_LIST allowed)
        string(REPLACE ";" ", " allowed_text "${allowed}")
        qa_fail("${file}" "${key} \"${value}\" is not one of: ${allowed_text}")
    endif()
endfunction()

# Parses one issue file into qa_<index>_<key> variables in the caller's scope.
function(qa_load_issue path dir index)
    get_filename_component(name "${path}" NAME)
    set(file "docs/qa/${dir}/${name}")

    foreach(key IN LISTS qa_all_keys)
        set(field_${key} "")
    endforeach()
    set(field_verify "")
    set(body_has_resolution OFF)

    file(STRINGS "${path}" lines)
    set(state "leading")
    set(current_list_key "")

    foreach(line IN LISTS lines)
        if(state STREQUAL "leading")
            if(line STREQUAL "---")
                set(state "frontmatter")
            elseif(NOT line STREQUAL "")
                qa_fail("${file}" "file must open with a `---` frontmatter block")
                set(state "body")
            endif()
        elseif(state STREQUAL "frontmatter")
            if(line STREQUAL "---")
                set(state "body")
            elseif(line MATCHES "^  *- +(.+)$")
                if(current_list_key STREQUAL "")
                    qa_fail("${file}" "list entry \"${line}\" has no owning key")
                else()
                    list(APPEND field_${current_list_key} "${CMAKE_MATCH_1}")
                endif()
            elseif(line MATCHES "^([a-z_]+): *(.*)$")
                set(key "${CMAKE_MATCH_1}")
                set(value "${CMAKE_MATCH_2}")
                string(STRIP "${value}" value)
                if(NOT key IN_LIST qa_all_keys)
                    string(REPLACE ";" ", " known_text "${qa_all_keys}")
                    qa_fail("${file}" "unknown frontmatter key \"${key}\" (known keys: ${known_text})")
                    set(current_list_key "")
                elseif(key IN_LIST qa_list_keys)
                    set(current_list_key "${key}")
                    if(NOT value STREQUAL "")
                        list(APPEND field_${key} "${value}")
                    endif()
                else()
                    set(current_list_key "")
                    if(NOT field_${key} STREQUAL "")
                        qa_fail("${file}" "duplicate frontmatter key \"${key}\"")
                    endif()
                    set(field_${key} "${value}")
                endif()
            elseif(NOT line STREQUAL "")
                qa_fail("${file}" "frontmatter line is not `key: value` or `  - item`: ${line}")
            endif()
        elseif(line MATCHES "^##[ \t]+Resolution")
            set(body_has_resolution ON)
        endif()
    endforeach()

    if(NOT state STREQUAL "body")
        qa_fail("${file}" "frontmatter block is never closed with `---`")
    endif()

    if(field_id STREQUAL "")
        qa_fail("${file}" "missing `id` — every issue needs a permanent QA-NNN id")
        set(qa_${index}_id "" PARENT_SCOPE)
        return()
    endif()
    if(NOT field_id MATCHES "^QA-[0-9][0-9][0-9]$")
        qa_fail("${file}" "id \"${field_id}\" must match QA-NNN (three digits, zero-padded)")
        set(qa_${index}_id "" PARENT_SCOPE)
        return()
    endif()
    if(NOT name MATCHES "^${field_id}-")
        qa_fail("${file}" "filename must start with \"${field_id}-\" so the id and file never drift apart")
    endif()

    foreach(key IN LISTS qa_required_keys)
        if(field_${key} STREQUAL "")
            qa_fail("${file}" "missing required field `${key}`")
        endif()
    endforeach()

    qa_check_enum("${file}" status "${field_status}" qa_statuses)
    qa_check_enum("${file}" severity "${field_severity}" qa_severities)
    qa_check_enum("${file}" confidence "${field_confidence}" qa_confidences)
    qa_check_enum("${file}" area "${field_area}" qa_areas)
    qa_check_enum("${file}" reporter "${field_reporter}" qa_reporters)

    if(field_reported AND NOT field_reported MATCHES "^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$")
        qa_fail("${file}" "reported \"${field_reported}\" must be YYYY-MM-DD")
    endif()
    if(field_closed AND NOT field_closed MATCHES "^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$")
        qa_fail("${file}" "closed \"${field_closed}\" must be YYYY-MM-DD")
    endif()

    # Placement and lifecycle: status must agree with the directory the file
    # sits in, or the index silently under-reports open work.
    set(is_open_status OFF)
    if(field_status IN_LIST qa_open_statuses)
        set(is_open_status ON)
    endif()
    if(is_open_status AND dir STREQUAL "closed")
        qa_fail("${file}" "status \"${field_status}\" is an open status but the file is in closed/")
    endif()
    if(NOT is_open_status AND field_status IN_LIST qa_statuses)
        if(dir STREQUAL "open")
            qa_fail("${file}" "status \"${field_status}\" is resolved — move the file to docs/qa/closed/")
        else()
            if(field_closed STREQUAL "")
                qa_fail("${file}" "resolved issues need a `closed:` date")
            endif()
            if(NOT body_has_resolution)
                qa_fail("${file}" "resolved issues need a `## Resolution` section recording the outcome")
            endif()
        endif()
    endif()

    foreach(entry IN LISTS field_verify)
        if(NOT entry MATCHES "^(wide_eye\\.|label:|target:|manual:)")
            qa_fail(
                "${file}"
                "verify entry \"${entry}\" must name a CTest test (wide_eye.*), a CTest label (label:unit), a build target (target:format-check), or manual evidence (manual:...)"
            )
        endif()
    endforeach()

    if(field_title STREQUAL "")
        set(field_title "(untitled)")
    endif()

    set(qa_${index}_dir "${dir}" PARENT_SCOPE)
    set(qa_${index}_name "${name}" PARENT_SCOPE)
    set(qa_${index}_file "${file}" PARENT_SCOPE)
    foreach(key IN LISTS qa_all_keys)
        set(qa_${index}_${key} "${field_${key}}" PARENT_SCOPE)
    endforeach()
endfunction()

# --- Load every issue -------------------------------------------------------

set(qa_count 0)
set(qa_open_indices "")
set(qa_closed_indices "")
set(qa_seen_ids "")

foreach(dir_name open closed)
    set(dir_path "${qa_dir}/${dir_name}")
    file(GLOB dir_files "${dir_path}/*.md")
    list(SORT dir_files)
    foreach(path IN LISTS dir_files)
        qa_load_issue("${path}" "${dir_name}" ${qa_count})
        if(NOT qa_${qa_count}_id STREQUAL "")
            if(qa_${qa_count}_id IN_LIST qa_seen_ids)
                qa_fail(
                    "${qa_${qa_count}_file}"
                    "duplicate id ${qa_${qa_count}_id} — ids are permanent and never reused"
                )
            else()
                list(APPEND qa_seen_ids "${qa_${qa_count}_id}")
            endif()
            if(dir_name STREQUAL "open")
                list(APPEND qa_open_indices ${qa_count})
            else()
                list(APPEND qa_closed_indices ${qa_count})
            endif()
            math(EXPR qa_count "${qa_count} + 1")
        endif()
    endforeach()
endforeach()

list(LENGTH qa_open_indices qa_open_count)
list(LENGTH qa_closed_indices qa_closed_count)

# --- next -------------------------------------------------------------------

if(MODE STREQUAL "next")
    get_property(qa_errors GLOBAL PROPERTY qa_errors)
    if(qa_errors)
        # A malformed existing file must never hand out a colliding id.
        message(FATAL_ERROR "QA tracker has errors; run the qa-check target first.")
    endif()
    set(highest 0)
    foreach(id IN LISTS qa_seen_ids)
        string(SUBSTRING "${id}" 3 -1 digits)
        string(REGEX REPLACE "^0+" "" digits "${digits}")
        if(digits STREQUAL "")
            set(digits 0)
        endif()
        if(digits GREATER highest)
            set(highest ${digits})
        endif()
    endforeach()
    math(EXPR next_number "${highest} + 1")
    if(next_number LESS 10)
        set(next_id "QA-00${next_number}")
    elseif(next_number LESS 100)
        set(next_id "QA-0${next_number}")
    else()
        set(next_id "QA-${next_number}")
    endif()
    message("${next_id}")
    return()
endif()

# --- Render the index -------------------------------------------------------

# Sorts a list of issue indices by permanent id.
function(qa_sort_indices indices_variable)
    set(pairs "")
    foreach(index IN LISTS ${indices_variable})
        list(APPEND pairs "${qa_${index}_id}=${index}")
    endforeach()
    list(SORT pairs)
    set(sorted "")
    foreach(pair IN LISTS pairs)
        string(REGEX REPLACE "^.*=" "" index "${pair}")
        list(APPEND sorted "${index}")
    endforeach()
    set(${indices_variable} "${sorted}" PARENT_SCOPE)
endfunction()

qa_sort_indices(qa_open_indices)
qa_sort_indices(qa_closed_indices)

set(rendered "# QA index\n")
string(APPEND rendered "\n")
string(APPEND rendered "<!-- GENERATED by tools/qa/qa-tracker.cmake — DO NOT EDIT. The issue files\n")
string(APPEND rendered "     in open/ and closed/ are the source of truth. Regenerate with the\n")
string(APPEND rendered "     qa-index target, or `cmake -DMODE=index -P tools/qa/qa-tracker.cmake`. -->\n")
string(APPEND rendered "\n")
string(APPEND rendered "**${qa_open_count} open** · ${qa_closed_count} closed · convention in [README.md](README.md)\n")
string(APPEND rendered "\n")

set(blocker_ids "")
foreach(index IN LISTS qa_open_indices)
    if(qa_${index}_severity STREQUAL "S1")
        list(APPEND blocker_ids "${qa_${index}_id}")
    endif()
endforeach()
list(LENGTH blocker_ids blocker_count)
if(blocker_count GREATER 0)
    string(REPLACE ";" ", " blocker_text "${blocker_ids}")
    set(plural "s")
    if(blocker_count EQUAL 1)
        set(plural "")
    endif()
    string(APPEND rendered "> **${blocker_count} tracer-gate blocker${plural} open.** ${blocker_text}\n")
else()
    string(APPEND rendered "> No tracer-gate blockers open.\n")
endif()
string(APPEND rendered "\n## Open\n\n")

if(qa_open_count EQUAL 0)
    string(APPEND rendered "_Nothing open. File with the `qa-intake` skill (`/qa`)._\n\n")
else()
    foreach(severity IN LISTS qa_severities)
        set(bucket "")
        foreach(index IN LISTS qa_open_indices)
            if(qa_${index}_severity STREQUAL "${severity}")
                list(APPEND bucket ${index})
            endif()
        endforeach()
        list(LENGTH bucket bucket_count)
        if(bucket_count GREATER 0)
            string(APPEND rendered "### ${qa_severity_label_${severity}}\n\n")
            foreach(index IN LISTS bucket)
                set(tags "${qa_${index}_area}" "${qa_${index}_confidence}")
                if(qa_${index}_status STREQUAL "in-progress")
                    list(APPEND tags "in progress")
                endif()
                if(qa_${index}_confidence STREQUAL "unconfirmed")
                    list(APPEND tags "needs owner repro")
                endif()
                string(REPLACE ";" " · " tag_text "${tags}")
                string(
                    APPEND rendered
                    "- [ ] [${qa_${index}_id}](open/${qa_${index}_name}) ${qa_${index}_title} — _${tag_text}_\n"
                )
            endforeach()
            string(APPEND rendered "\n")
        endif()
    endforeach()
endif()

string(APPEND rendered "## By area\n\n")
string(APPEND rendered "| Area | Open | Closed |\n")
string(APPEND rendered "| --- | --- | --- |\n")
foreach(area IN LISTS qa_areas)
    set(area_open 0)
    set(area_closed 0)
    foreach(index IN LISTS qa_open_indices)
        if(qa_${index}_area STREQUAL "${area}")
            math(EXPR area_open "${area_open} + 1")
        endif()
    endforeach()
    foreach(index IN LISTS qa_closed_indices)
        if(qa_${index}_area STREQUAL "${area}")
            math(EXPR area_closed "${area_closed} + 1")
        endif()
    endforeach()
    if(area_open GREATER 0 OR area_closed GREATER 0)
        string(APPEND rendered "| ${area} | ${area_open} | ${area_closed} |\n")
    endif()
endforeach()
string(APPEND rendered "\n## Closed\n\n")

if(qa_closed_count EQUAL 0)
    string(APPEND rendered "_Nothing closed yet._\n")
else()
    list(REVERSE qa_closed_indices)
    foreach(index IN LISTS qa_closed_indices)
        set(outcome "${qa_${index}_status}")
        if(qa_${index}_closed)
            set(outcome "${outcome} ${qa_${index}_closed}")
        endif()
        string(
            APPEND rendered
            "- [x] [${qa_${index}_id}](closed/${qa_${index}_name}) ${qa_${index}_title} — _${outcome}_\n"
        )
    endforeach()
endif()

# --- check / index ----------------------------------------------------------

get_property(qa_errors GLOBAL PROPERTY qa_errors)

if(MODE STREQUAL "check")
    set(current "")
    if(EXISTS "${qa_index_path}")
        file(READ "${qa_index_path}" current)
    endif()
    if(NOT current STREQUAL rendered)
        list(APPEND qa_errors "docs/qa/INDEX.md: stale — regenerate with the qa-index target")
    endif()
    if(qa_errors)
        list(LENGTH qa_errors error_count)
        set(report "QA tracker check FAILED (${error_count}):")
        foreach(error IN LISTS qa_errors)
            string(APPEND report "\n  - ${error}")
        endforeach()
        message(FATAL_ERROR "${report}")
    endif()
    message("QA tracker check passed: ${qa_open_count} open, ${qa_closed_count} closed.")
    return()
endif()

if(qa_errors)
    list(LENGTH qa_errors error_count)
    set(report "Refusing to write INDEX.md — ${error_count} issue file error(s):")
    foreach(error IN LISTS qa_errors)
        string(APPEND report "\n  - ${error}")
    endforeach()
    message(FATAL_ERROR "${report}")
endif()

file(WRITE "${qa_index_path}" "${rendered}")
message("Wrote docs/qa/INDEX.md — ${qa_open_count} open, ${qa_closed_count} closed.")
