include_guard(GLOBAL)

include(FetchContent)

set(wide_eye_glad_root "${PROJECT_SOURCE_DIR}/third_party/glad")

function(wide_eye_verify_dependency_file relative_path expected_sha256)
    set(dependency_path "${wide_eye_glad_root}/${relative_path}")
    if(NOT EXISTS "${dependency_path}")
        message(FATAL_ERROR "Pinned glad input is missing: ${dependency_path}")
    endif()

    file(SHA256 "${dependency_path}" actual_sha256)
    if(NOT actual_sha256 STREQUAL expected_sha256)
        message(
            FATAL_ERROR
            "Pinned glad input checksum mismatch for ${relative_path}: expected ${expected_sha256}, got ${actual_sha256}"
        )
    endif()
endfunction()

# Generated by checksum-pinned glad 2.0.8 for OpenGL 4.6 Core with no
# extensions. See third_party/glad/README.md for provenance and regeneration.
wide_eye_verify_dependency_file(
    "LICENSE"
    "cbb325cd4ac5bd06717ffa34a322b984f9d285e4c67c8ca1b7380d6ef08c2a77"
)
wide_eye_verify_dependency_file(
    "include/KHR/khrplatform.h"
    "7b1e01aaa7ad8f6fc34b5c7bdf79ebf5189bb09e2c4d2e79fc5d350623d11e83"
)
wide_eye_verify_dependency_file(
    "include/glad/gl.h"
    "0e1ac72e82aec8ab8d1fe176e46a471643c9673b03ba42c4df6dea89d2f0e7f5"
)
wide_eye_verify_dependency_file(
    "src/gl.c"
    "07cf9e52e7c018a1e5a8fde75bfe63f0527b3963b9f5f6219ae04924fbe934c1"
)

add_library(wide_eye_glad STATIC "${wide_eye_glad_root}/src/gl.c")
target_include_directories(wide_eye_glad SYSTEM PUBLIC "${wide_eye_glad_root}/include")
add_library(glad::glad ALIAS wide_eye_glad)

set(SDL_SHARED ON CACHE BOOL "Build SDL as a shared library" FORCE)
set(SDL_STATIC OFF CACHE BOOL "Do not build a second static SDL library" FORCE)
set(SDL_TESTS OFF CACHE BOOL "Do not build SDL's own test suite" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "Do not build SDL's test support library" FORCE)
set(SDL_EXAMPLES OFF CACHE BOOL "Do not build SDL examples" FORCE)
set(SDL_INSTALL OFF CACHE BOOL "Do not add SDL install rules to the game build" FORCE)
set(SDL_UNINSTALL OFF CACHE BOOL "Do not add SDL uninstall rules to the game build" FORCE)

# Tracer 1 adds standardized keyboard/gamepad actions. Audio and unrelated SDL
# subsystems remain outside the current outcome.
set(SDL_AUDIO OFF CACHE BOOL "Audio is outside the current tracer" FORCE)
set(SDL_CAMERA OFF CACHE BOOL "Camera capture is outside the current tracer" FORCE)
set(SDL_DIALOG OFF CACHE BOOL "Native dialogs are outside the current tracer" FORCE)
set(SDL_GPU OFF CACHE BOOL "The engine uses its own OpenGL renderer" FORCE)
set(SDL_HAPTIC OFF CACHE BOOL "Haptics are outside the current tracer" FORCE)
set(SDL_JOYSTICK ON CACHE BOOL "Controller input is required by the dog tracer" FORCE)
set(SDL_RENDER OFF CACHE BOOL "The engine uses its own OpenGL renderer" FORCE)
set(SDL_SENSOR OFF CACHE BOOL "Sensors are outside the current tracer" FORCE)
set(SDL_TRAY OFF CACHE BOOL "Tray integration is outside the current tracer" FORCE)
set(SDL_WAYLAND OFF CACHE BOOL "The current Linux development path uses X11" FORCE)
set(SDL_KMSDRM OFF CACHE BOOL "Direct KMS/DRM is outside the current tracer" FORCE)

FetchContent_Declare(
    SDL3
    URL https://github.com/libsdl-org/SDL/releases/download/release-3.4.10/SDL3-3.4.10.tar.gz
    URL_HASH SHA256=12b34280415ec8418c864408b93d008a20a6530687ee613d60bfbd20411f2785
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    EXCLUDE_FROM_ALL
)
FetchContent_MakeAvailable(SDL3)

if(NOT TARGET SDL3::SDL3)
    message(FATAL_ERROR "Pinned SDL 3.4.10 did not provide the SDL3::SDL3 target")
endif()

# MSVC cannot create SDL's generated PCH reliably when the WSL workspace is
# exposed through a temporary pushd drive. Ordinary source/object paths work,
# so keep the safer workspace-local native verification path and trade only
# dependency build speed on Windows.
if(WIN32 AND TARGET SDL3-shared)
    set_property(TARGET SDL3-shared PROPERTY DISABLE_PRECOMPILE_HEADERS ON)
endif()
